### ISSUE TITLE
Add cooldowns on events

### ISSUE THREAD

**Issue by Satont** [Satont/yakui#301]
Right now there is no cooldowns for TTS, Play sound operations.

We should add cooldowns to prevent spam.

**Comment by AlexWayfer** [comment]
I think we don't need for this.

1. "Cooldowns" are ending points and reward costs.
2. Yeah, sometimes somebody can have a lot of points and spam, but cooldowns for this should be implemented on Twitch side. Otherwise, when you lost channel points and here is no your reward in-time — it's confusing.

**Comment by Satont** [comment]
Thats funny and this issue now have no point, but right 5 hours ago twitch posted such tweet: https://twitter.com/TwitchSupport/status/1311055756922359808?s=19

**Comment by AlexWayfer** [comment]
Twitch stuff is watching you. 👀
